name: Auto Approve

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    if: ${{ contains(fromJSON(vars.TRUSTED_ACTORS), github.actor) }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: actions/github-script@v7
        id: check-changes
        with:
          script: |
            const { execSync } = require('child_process')
            const { commits } = context.payload.pull_request
            const rawFiles = execSync(`git diff --name-only HEAD HEAD~${commits}`).toString()
            const files = rawFiles.split('\n').filter(Boolean)
            const eligible = files.every(file => file.startsWith('schedules/') && file.endsWith('.toml'))

            if (!eligible) {
              const message = 'This PR modifies files outside of the schedules directory or adds files with an invalid extension.'
              core.setFailed(message)
            }

      - uses: hmarr/auto-approve-action@v4
        if: ${{ success() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ success() }}
        run: gh pr merge --squash --auto ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
