name: Auto Approve

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    if: ${{ contains(fromJSON(vars.TRUSTED_ACTORS), github.actor) }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/github-script@v7
        id: check-changes
        with:
          script: |
            const { execSync } = require('child_process')
            const { commits } = context.payload.pull_request
            const rawFiles = execSync(`git diff --name-only HEAD HEAD~${commits}`).toString()
            const files = rawFiles.split('\n').filter(Boolean)

            console.log(files)

            return {
              success: files.length === 1 && files[0] === 'schedule.toml'
            }
          result-encoding: json

      - uses: hmarr/auto-approve-action@v4
        if: steps.check-changes.outputs.result.success
