name: Auto Approve

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    if: ${{ contains(fromJSON(vars.TRUSTED_ACTORS), github.actor) }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/github-script@v7
        id: check-changes
        with:
          script: |
            const { execSync } = require('child_process')
            const { commits } = context.payload.pull_request
            const rawFiles = execSync(`git diff --name-only HEAD HEAD~${commits}`).toString()
            const files = rawFiles.split('\n').filter(Boolean)
            const eligible = files.length === 1 && files[0] === 'schedule.toml'

            if (!eligible) {
              const message = 'This PR does modify files other than `schedule.toml` or the commit is empty.'
              core.setFailed(message)
            }

      - uses: hmarr/auto-approve-action@v4
        if: ${{ success() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        if: ${{ success() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

      - name: Merge Pull Request
        uses: peter-evans/merge-pull-request@v3
        if: ${{ success() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: ${{ github.event.pull_request.number }}
          merge-method: squash
